### ISSUE TITLE
Not honoring subreddit

### ISSUE THREAD

**Issue by phurious** [bbilly1/reddit-bot#3]
Thank you for sharing! Having a bit of an issue with the script respecting the sudreddit defined in either the env file or being passed in the docker-compose file. Currently it appears to be pulling in topics from all over reddit.

**Comment by bbilly1** [comment]
I think there is a misunderstanding. This little script is doing two things:

- Monitor a Subreddit and notify for all comments
- Monitor Reddit for any keyword mentions in comments or post

Maybe should clarify that better:
- Monitor a *single* Subreddit and notify for all comments
- Monitor *all of* Reddit for any keyword mentions in comments or post
